version: '3.8'

services:
  postgres:
    image: postgres
    container_name: money_bot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: money_bot
    ports:
      - "5436:5436"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
